sudo: false

language: php

env:
    global:
        - ELASTICSEARCH_URL=http://localhost:9200

php:
    - '7.0'
    - '7.1'
    - 'nightly'

before_install:
    - wget https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/zip/elasticsearch/2.4.5/elasticsearch-2.4.5.zip
    - unzip elasticsearch-2.4.5.zip
    - ./elasticsearch-2.4.5/bin/elasticsearch &

install:
    - composer install --no-interaction

script:
    - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
    - bin/phing all

notifications:
    email: false
